services:
  rabbitmq:
    image: rabbitmq:3-alpine
    container_name: polis-pro-reminder-rabbitmq
    ports:
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    networks:
      - rabbitmq_network

  mailer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: polis-pro-reminder-mailer
    restart: always
    env_file:
      - .env
    depends_on:
      - rabbitmq
    networks:
      - rabbitmq_network

networks:
  rabbitmq_network:
    driver: bridge
