name: polisproreminder-mailer-dev
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: polis-pro-reminder-rabbitmq-dev
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - rabbitmq_network

  mailer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: polis-pro-reminder-mailer-dev
    restart: always
    env_file:
      - .env.dev
    depends_on:
      - rabbitmq
    networks:
      - rabbitmq_network
    links:
      - rabbitmq

networks:
  rabbitmq_network:
    driver: bridge