name: Deploy to Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Stop docker containers
        run: |
          sudo docker stop `sudo docker ps -a -q`

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Copy .env file
        run: |
          cp /var/www/mailer/.env .
          echo "Copied .env file from /var/www/mailer/ to the current directory."

      - name: Build and run Docker containers
        run: |
          docker-compose up -d --build

      - name: Start docker containers
        run: |
          sudo docker start `sudo docker ps -a -q`

      - name: Check status
        run: docker-compose ps
